// Auto-generated by obj2environment.py
// DO NOT EDIT the ENVIRONMENT blocks by hand - regenerate from source .obj files.
#include "data/environmentDb.hpp"

// === ENVIRONMENT: iwatodai_dorm_floor_1 BEGIN ===
static const EnvironmentTexture iwatodai_dorm_floor_1_textures[32] = {
    {"f007_002wall01.img.bin", 64, 64, NULL},  // f007_002wall01.png
    {"f007_002wall02.img.bin", 64, 64, NULL},  // f007_002wall02.png
    {"f007_002wall03.img.bin", 32, 32, NULL},  // f007_002wall03.png
    {"f007_002door02.img.bin", 64, 64, NULL},  // f007_002door02.png
    {"f007_002kzr01.img.bin", 64, 64, NULL},   // f007_002kzr01.png
    {"f007_002kzr02.img.bin", 64, 64, NULL},   // f007_002kzr02.png
    {"f007_002obj01.img.bin", 64, 64, NULL},   // f007_002obj01.png
    {"f007_002obj04.img.bin", 64, 64, NULL},   // f007_002obj04.png
    {"f007_002obj07.img.bin", 64, 64, NULL},   // f007_002obj07.png
    {"f007_002obj11.img.bin", 64, 64, NULL},   // f007_002obj11.png
    {"f007_002wall04.img.bin", 32, 32, NULL},  // f007_002wall04.png
    {"f007_002wall05.img.bin", 64, 64, NULL},  // f007_002wall05.png
    {"f007_002wall06.img.bin", 32, 32, NULL},  // f007_002wall06.png
    {"f007_002step01.img.bin", 64, 64, NULL},  // f007_002step01.png
    {"f007_002step02.img.bin", 32, 32, NULL},  // f007_002step02.png
    {"f007_002kzr03.img.bin", 64, 64, NULL},   // f007_002kzr03.png
    {"f007_002kzr04.img.bin", 64, 64, NULL},   // f007_002kzr04.png
    {"f007_002obj09.img.bin", 64, 64, NULL},   // f007_002obj09.png
    {"f007_002bolt01.img.bin", 64, 64, NULL},  // f007_002bolt01.png
    {"f007_002obj03.img.bin", 64, 64, NULL},   // f007_002obj03.png
    {"f007_002floor01.img.bin", 64, 64, NULL}, // f007_002floor01.png
    {"f007_002floor02.img.bin", 64, 64, NULL}, // f007_002floor02.png
    {"f007_002floor03.img.bin", 64, 64, NULL}, // f007_002floor03.png
    {"f007_002obj02.img.bin", 64, 64, NULL},   // f007_002obj02.png
    {"f007_002obj05.img.bin", 64, 64, NULL},   // f007_002obj05.png
    {"f007_002obj15.img.bin", 64, 64, NULL},   // f007_002obj15.png
    {"f007_002bolt03.img.bin", 32, 32, NULL},  // f007_002bolt03.png
    {"f007_002obj13.img.bin", 64, 64, NULL},   // f007_002obj13.png
    {"f007_002obj12.img.bin", 32, 32, NULL},   // f007_002obj12.png
    {"f007_002door01.img.bin", 64, 64, NULL},  // f007_002door01.png
    {"f007_002obj10.img.bin", 64, 64, NULL},   // f007_002obj10.png
    {"akihiko.img.bin", 32, 64, NULL},         // akihiko.png
};

static const BillboardData iwatodai_dorm_floor_1_billboards[1] = {
    {"Akihiko_Plane.001",
     ae::q4_12_t::from_raw_value(2641),
     ae::q4_12_t::from_raw_value(751),
     ae::q4_12_t::from_raw_value(5320),
     ae::q4_12_t::from_raw_value(360),
     ae::q4_12_t::from_raw_value(733),
     31,
     ae::q12_4_t::from_raw_value(0),
     ae::q12_4_t::from_raw_value(0),
     ae::q12_4_t::from_raw_value(512),
     ae::q12_4_t::from_raw_value(1024)},
};

const EnvironmentDbEntry iwatodai_dorm_floor_1EnvironmentDbEntry = {
    "iwatodai_dorm_floor_1",
    "iwatodai_dorm_floor_1.bin",
    ae::q20_12_t::from_raw_value(9190),
    ae::q20_12_t::from_raw_value(14336),
    ae::q20_12_t::from_raw_value(18379),
    ae::q20_12_t::from_raw_value(28672),
    32,
    iwatodai_dorm_floor_1_textures,
    1,
    iwatodai_dorm_floor_1_billboards,
};
// === ENVIRONMENT: iwatodai_dorm_floor_1 END ===

// === ENVIRONMENT: iwatodai_streets BEGIN ===
static const EnvironmentTexture iwatodai_streets_textures[22] = {
    {"f007_009_24.img.bin", 64, 64, NULL}, // f007_009_24.png
    {"f007_009_01.img.bin", 64, 64, NULL}, // f007_009_01.png
    {"f007_009_07.img.bin", 64, 64, NULL}, // f007_009_07.png
    {"f007_009_08.img.bin", 64, 64, NULL}, // f007_009_08.png
    {"f007_009_09.img.bin", 64, 64, NULL}, // f007_009_09.png
    {"f007_009_10.img.bin", 64, 64, NULL}, // f007_009_10.png
    {"f007_009_02.img.bin", 64, 64, NULL}, // f007_009_02.png
    {"f007_009_16.img.bin", 64, 64, NULL}, // f007_009_16.png
    {"f007_009_25.img.bin", 32, 64, NULL}, // f007_009_25.png
    {"f007_009_23.img.bin", 64, 64, NULL}, // f007_009_23.png
    {"f007_009_04.img.bin", 64, 64, NULL}, // f007_009_04.png
    {"f007_009_05.img.bin", 64, 64, NULL}, // f007_009_05.png
    {"f007_009_30.img.bin", 64, 64, NULL}, // f007_009_30.png
    {"f007_009_28.img.bin", 64, 64, NULL}, // f007_009_28.png
    {"f007_009_27.img.bin", 64, 64, NULL}, // f007_009_27.png
    {"f007_009_11.img.bin", 64, 64, NULL}, // f007_009_11.png
    {"f007_009_03.img.bin", 64, 64, NULL}, // f007_009_03.png
    {"f007_009_13.img.bin", 64, 64, NULL}, // f007_009_13.png
    {"f007_009_12.img.bin", 64, 64, NULL}, // f007_009_12.png
    {"f007_009_17.img.bin", 64, 64, NULL}, // f007_009_17.png
    {"f007_009_18.img.bin", 64, 64, NULL}, // f007_009_18.png
    {"enemy.img.bin", 64, 64, NULL},       // enemy.png
};

static const BillboardData iwatodai_streets_billboards[1] = {
    {"Enemy_Plane.002",
     ae::q4_12_t::from_raw_value(70),
     ae::q4_12_t::from_raw_value(518),
     ae::q4_12_t::from_raw_value(3367),
     ae::q4_12_t::from_raw_value(784),
     ae::q4_12_t::from_raw_value(518),
     21,
     ae::q12_4_t::from_raw_value(0),
     ae::q12_4_t::from_raw_value(0),
     ae::q12_4_t::from_raw_value(1024),
     ae::q12_4_t::from_raw_value(1024)},
};

const EnvironmentDbEntry iwatodai_streetsEnvironmentDbEntry = {
    "iwatodai_streets",
    "iwatodai_streets.bin",
    ae::q20_12_t::from_raw_value(20480),
    ae::q20_12_t::from_raw_value(11540),
    ae::q20_12_t::from_raw_value(40960),
    ae::q20_12_t::from_raw_value(23080),
    22,
    iwatodai_streets_textures,
    1,
    iwatodai_streets_billboards,
};
// === ENVIRONMENT: iwatodai_streets END ===

// === ENVIRONMENT: paulownia_mall BEGIN ===
static const EnvironmentTexture paulownia_mall_textures[31] = {
    {"f008_001_fl02.img.bin", 32, 32, NULL},     // f008_001_fl02.png
    {"f008_001_fl03.img.bin", 32, 32, NULL},     // f008_001_fl03.png
    {"f008_001_gsfl.img.bin", 16, 32, NULL},     // f008_001_gsfl.png
    {"f008_001_hasira.img.bin", 32, 16, NULL},   // f008_001_hasira.png
    {"f008_001_kaidan.img.bin", 32, 16, NULL},   // f008_001_kaidan.png
    {"f008_001_sky.img.bin", 32, 32, NULL},      // f008_001_sky.png
    {"f008_001_wl01.img.bin", 32, 32, NULL},     // f008_001_wl01.png
    {"f008_001_wl02.img.bin", 32, 32, NULL},     // f008_001_wl02.png
    {"f008_001_komono01.img.bin", 32, 32, NULL}, // f008_001_komono01.png
    {"f008_001_fun03.img.bin", 32, 16, NULL},    // f008_001_fun03.png
    {"f008_001_komono02.img.bin", 32, 32, NULL}, // f008_001_komono02.png
    {"f008_001_ligfla.img.bin", 32, 16, NULL},   // f008_001_ligfla.png
    {"f008_001_enter02.img.bin", 32, 32, NULL},  // f008_001_enter02.png
    {"f008_001_plantA.img.bin", 32, 32, NULL},   // f008_001_plantA.png
    {"f008_001_keimark.img.bin", 32, 32, NULL},  // f008_001_keimark.png
    {"f008_001_jyutan.img.bin", 32, 16, NULL},   // f008_001_jyutan.png
    {"f008_001_fl01.img.bin", 32, 16, NULL},     // f008_001_fl01.png
    {"f008_001_hiho.img.bin", 32, 32, NULL},     // f008_001_hiho.png
    {"f008_001_kanban03.img.bin", 32, 8, NULL},  // f008_001_kanban03.png
    {"f008_001_kanban.img.bin", 32, 32, NULL},   // f008_001_kanban.png
    {"f008_001_fun01.img.bin", 32, 32, NULL},    // f008_001_fun01.png
    {"f008_001_fun02.img.bin", 32, 32, NULL},    // f008_001_fun02.png
    {"f008_001_acyane.img.bin", 32, 32, NULL},   // f008_001_acyane.png
    {"f008_001_enter01.img.bin", 32, 32, NULL},  // f008_001_enter01.png
    {"f008_001_kar.img.bin", 32, 32, NULL},      // f008_001_kar.png
    {"f008_001_glass.img.bin", 16, 32, NULL},    // f008_001_glass.png
    {"f008_001_chair.img.bin", 32, 16, NULL},    // f008_001_chair.png
    {"f008_001_gafl.img.bin", 32, 32, NULL},     // f008_001_gafl.png
    {"f008_001_cd.img.bin", 32, 32, NULL},       // f008_001_cd.png
    {"f008_001_kanban02.img.bin", 32, 32, NULL}, // f008_001_kanban02.png
    {"f008_001_gra02.img.bin", 32, 32, NULL},    // f008_001_gra02.png
};

const EnvironmentDbEntry paulownia_mallEnvironmentDbEntry = {
    "paulownia_mall",
    "paulownia_mall.bin",
    ae::q20_12_t::from_raw_value(24576),
    ae::q20_12_t::from_raw_value(17815),
    ae::q20_12_t::from_raw_value(49152),
    ae::q20_12_t::from_raw_value(35630),
    31,
    paulownia_mall_textures,
    0,
    NULL,
};
// === ENVIRONMENT: paulownia_mall END ===

// === ENVIRONMENT: station BEGIN ===
static const EnvironmentTexture station_textures[11] = {
    {"f008_005obj04.img.bin", 64, 64, NULL},   // f008_005obj04.png
    {"f008_005obj02.img.bin", 64, 64, NULL},   // f008_005obj02.png
    {"f008_005obj07.img.bin", 64, 64, NULL},   // f008_005obj07.png
    {"f008_005obj06.img.bin", 64, 64, NULL},   // f008_005obj06.png
    {"f008_005obj08.img.bin", 64, 64, NULL},   // f008_005obj08.png
    {"lightmap_white.img.bin", 32, 32, NULL},  // lightmap_white.png
    {"f008_005wall01.img.bin", 64, 64, NULL},  // f008_005wall01.png
    {"f008_005obj01.img.bin", 64, 64, NULL},   // f008_005obj01.png
    {"f008_005obj03.img.bin", 64, 64, NULL},   // f008_005obj03.png
    {"f008_005floor01.img.bin", 64, 64, NULL}, // f008_005floor01.png
    {"f008_005bolt01.img.bin", 64, 64, NULL},  // f008_005bolt01.png
};

const EnvironmentDbEntry stationEnvironmentDbEntry = {
    "station",
    "station.bin",
    ae::q20_12_t::from_raw_value(5257),
    ae::q20_12_t::from_raw_value(12288),
    ae::q20_12_t::from_raw_value(10514),
    ae::q20_12_t::from_raw_value(24576),
    11,
    station_textures,
    0,
    NULL,
};
// === ENVIRONMENT: station END ===

const EnvironmentDbEntry* g_environmentDb[4] = {
    &iwatodai_dorm_floor_1EnvironmentDbEntry,
    &iwatodai_streetsEnvironmentDbEntry,
    &paulownia_mallEnvironmentDbEntry,
    &stationEnvironmentDbEntry,
};

const int g_environmentDbCount = 4;
